baseurl = "https://sfyntank.github.io/website/"
languageCode = "en-us"
title = "SFYN TANK"
theme = "sfynTank"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the challenges are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "SFYN JAM"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "SFYN TANK"

		[params.navigation.links]
			about     = "About"
			info  = "Infos"
			challenges = "Challenges"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "*an open think to our food system"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "SFYN Tank is an experimental think-tank to our greater Slow Food mechanism; an idea-generation and solution-design based event to influence which social initiatives Slow Food can spearhead within the context of our global food movement."

		description = "With the input of interaction designers, product designers, and food designers, alongside the gastronomic expertise of our Slow Food Youth Network delegates and members, we can innovate solutions to social food problems. Come attend our full-day design workshop on September 24th, 2016 to employ a multidisciplinary approach that encompasses studying, storytelling, and thinking with a critical design eye to solve nine social problems our food system faces--from shifting our idea of meat consumption to considering how to integrate the food culture of migrants. Through open-exchange of expertise, out-of-the-box thinking, and a design approach, we can make meaningful impact on our global food system.  "

		buttonText  = "Think with us. Tank with SFYN."


	# info section
	[params.infos]
		headline = "All you need to know"

		[[params.infos.list]]
				icon = "fa-heart"
				title = "What?"
				description = "Full-day social-design workshop to tackle 9 food issues."

    [[params.infos.list]]
        icon = "fa-map-signs"
        title = "where?"
        description = "Toolbox office lab and co-working space. Via Egeo 16 Torino"

    [[params.infos.list]]
			icon = "fa-calendar"
			title = "when?"
			description = "Saturday, September 24th, Terra Madre e Salone del Gusto 2016"

		[[params.infos.list]]
      icon = "fa-group"
      title = "who?"
      description = "100+ grassroots food producers from the SFYN network and academic and industry designers"


    # Portfolio modals
	[params.challenges]
				title= "The tank issues"

	[params.challenges.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "123-456-6789"
		email = "feedback@startbootstrap.com"
