baseurl = "http://www.sfyntank.com/"
languageCode = "en-us"
title = "SFYN TANK"
theme = "sfynTank"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the challenges are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "SFYN JAM"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "SFYN TANK"

		[params.navigation.links]
			about     = "About"
			info  = "Infos"
			challenges = "Challenges"
			contact   = "Join us"
			program   = "Program"
			faq = "F.A.Q."


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "*Think up solutions to food issues"
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Join a free, full day social-design workshop on 9 food issues with some of the most engaging people in grassroots food work and creativity!"

		description = "Innovate solutions to social food problems! With the input of creatives--including interaction and product designers--alongside grassroots, gastronomic experts within the Slow Food Youth Network, you can impact future food initiatives! SFYN Tank is an experimental event aimed at squaring open-exchange of expertise at the center of food activism. Aimed at anyone in grassroots food work or creative sectors, we hope to engage food enthusiasts in collective problem-solving through design-thinking. Come attend our full day social-design workshop on September 24th, 2016 to employ a multidisciplinary approach that encompasses research, storytelling, idea-generation, and prototyping with a critical design eye to solve nine social problems our food system faces–from shifting our idea of seafood consumption to democratizing food communication. Through open-exchange of expertise, out-of-the-box thinking, and a design approach, we truly can make meaningful impact on our global food system."

		buttonText  = "Think with us. Tank with SFYN!"


	# info section
	[params.infos]
		headline = "All you need to know"

		[[params.infos.list]]
				icon = "fa-pencil"
				title = "what?"
				description = "Full-day design workshop to tackle 9 food issues"

    [[params.infos.list]]
        icon = "fa-map-signs"
        title = "where?"
        description = "<a href='http://www.toolboxoffice.it' target='_blank'>Toolbox</a> office lab and co-working space. <a href='https://www.google.it/maps/place/Toolbox+Coworking/@45.050238,7.6670973,17z/data=!3m1!4b1!4m5!3m4!1s0x47886d37dd5ababd:0x2adc0b0e358ddb6c!8m2!3d45.050238!4d7.669286?hl=en' target='_blank'>Via Agostino da Montefeltro 2,Torino</a>"

    [[params.infos.list]]
			icon = "fa-calendar"
			title = "when?"
			description = "Saturday, September 24th, <a href='http://www.terramadre.info/en/' target='_blank'>Terra Madre Salone del Gusto 2016</a>"

		[[params.infos.list]]
      icon = "fa-group"
      title = "who?"
      description = "99 tankers  | 9 issue coaches | 9 life-line experts"


    # Portfolio modals
	[params.challenges]
				title= "The tank issues"
				subtitle= "9 ISSUES 9 TABLES NINETY-NINE PLACES"
				sentence= "*Read through the issues below and request your place at a table."


	[params.challenges.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Think with us. Tank with SFYN."
		description = "Join a full-day brainstorm and solution-development workshop on 9 food issues with some of the most interesting people in grassroots food production and design!"
		[[params.contact.buttons]]
		buttonText = "REQUEST A PLACE"
		buttonLink="https://marianna28.typeform.com/to/jWQtou"
		[[params.contact.buttons]]
		buttonText = "JOIN AS VOLUNTEER"
		buttonLink="https://marianna28.typeform.com/to/mHrflb"


		# Plug section
		[params.plug]
			headline = "Plug into the Tank"
			email="info@sfintank.com"

			[[params.plug.social]]
			social = "facebook"
			icon=  "fa-facebook"
			link = "https://www.facebook.com/slowfoodyouthnetwork/?fref=ts"
			[[params.plug.social]]
			social = "instagram"
			icon=  "fa-instagram"
			link = "https://www.instagram.com/slowfoodyouthnetwork/#/"
			[[params.plug.social]]
			social = "twitter"
			icon=  "fa-twitter"
			link = "https://twitter.com/sfynetwork?lang=it"


		[params.credits]

			[[params.credits.list]]
			headline= "Orgnanized By"

			[[params.credits.list.partner]]
				name= "Casa Jasmina"
				website= "http://casajasmina.arduino.cc"
				logo= "cj.png"

				[[params.credits.list.partner]]
				name= "SFYN"
				website= "???"
				logo= "sfyn.png"

				[[params.credits.list.partner]]
				name= "food hub"
				website= "http://food-hub.org/"
				logo= "foodHub.png"

			[[params.credits.list]]
			headline= "Supported By"

				[[params.credits.list.partner]]
				name= "hivos"
				website= "https://www.hivos.org/"
				logo= "hivos.png"

				[[params.credits.list.partner]]
				name= "Terra Madre Salone del Gusto"
				website= "http://www.salonedelgusto.com/en/"
				logo= "terraMadre.png"

				[[params.credits.list]]
				headline= "Hosted By"

					[[params.credits.list.partner]]
					name= "toolbox"
					website= "http://toolboxoffice.it"
					logo= "toolbox.png"
